name:                collect
version:             0.1.0.0
github:              "ddubson/collect"
license:             BSD3
author:              "Dmitriy Dubson"
maintainer:          "d.dubson@gmail.com"
copyright:           "2020 Dmitriy Dubson"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/ddubson/collect#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3.3.0
- containers >= 0.6.0.1
- QuickCheck >= 2.13.2

library:
  source-dirs: src

executables:
  collect:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - collect
    - directory
    - containers

tests:
  collect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - collect
    - hspec
    - QuickCheck
